import os

def sync_env():
    ui_env_path = "/home/enn/workspace/PostExtraction/.env"
    ext_env_path = "/home/enn/workspace/PostExtraction/facebook-apify-extension/env.js"
    
    if not os.path.exists(ui_env_path):
        print(f"Error: {ui_env_path} not found")
        return

    url = ""
    key = ""
    
    with open(ui_env_path, 'r') as f:
        for line in f:
            if line.startswith("VITE_SUPABASE_URL="):
                url = line.split("=")[1].strip().strip('"').strip("'")
            elif line.startswith("VITE_SUPABASE_ANON_KEY="):
                key = line.split("=")[1].strip().strip('"').strip("'")
    
    if not url or not key:
        print("Error: Could not find Supabase URL or Key in .env")
        return

    content = f"""// This file is generated from root .env
// Do not edit this file directly. Run sync_env.py to update.
const SUPABASE_CONFIG = {{
    URL: "{url}",
    KEY: "{key}"
}};
"""
    
    with open(ext_env_path, 'w') as f:
        f.write(content)
    
    print(f"Successfully synced {ext_env_path}")

if __name__ == "__main__":
    sync_env()
